### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by hashimo1013** [hashimo1013/chat-space#11]
# IPアドレス
3.114.181.163

**Comment by naru6117** [comment]
橋本さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
左側のグループ表示の部分にて、グループ名が中央揃えになっている
※正しくはこちらの指示書をご確認ください。
https://tech-master.s3.amazonaws.com/uploads/curriculums//03e925297f3843c603f028b177b4e86b.png

それ以外は完璧でした！
あと少し頑張りましょう！

修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by hashimo1013** [comment]
修正しました！
イキッてh1タグを使ったために勝手にtext-align:center が付与されてるのが原因でした！

**Comment by naru6117** [comment]
橋本さん、早速の修正とご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！お疲れさまでした！
しっかり原因を把握して修正ができているのが素晴らしいですね！
